### ISSUE TITLE
parity_setTransactionsLimit is deprecated and needs replacement

### ISSUE THREAD

**Issue by jordipainan** [openethereum/openethereum#10358]
- **Parity Ethereum version**: v2.1.10-stable-b47e064f8-20181213
- **Operating system**: x86_64-macos/rustc1.31.0
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum dev
- **Restarted**: no / yes

- **actual** 
```
MacBook-Air-de-Jordi:rust-web3 jordi$ curl --data '{"method":"parity_setTransactionsLimit","params":["0x3e8"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: invalid type: string \"0x3e8\", expected usize."},"id":1}
```
- **expected behavior**
```
{"jsonrpc":"2.0","result":true,"id":1}
```
- **steps to reproduce** the issue.
```
parity --chain dev
curl --data '{"method":"parity_setTransactionsLimit","params":["0x3e8"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```

**Comment by tomusdrw** [comment]
The method is deprecated anyway since it doesn fully match current transaction pool method. If you feel you need to control transaction pool limit over RPC, please open a separate issue, we will think of a way how to revive it (basically there are multiple limits in place currently, it would be good to have one RPC method for everything).

@joshua-mir would you mind updating the docs?

**Comment by jordipainan** [comment]
Actually I don't need to control the transaction pool limit over RPC. I noticed the method not working when implementing `parity_set`.
I don't think its a must or a core feature to be solved right now, but yes! would be nice to have one RPC method for all this related things. We can think about that.

**Comment by adria0** [comment]
Closing issue due to its stale state.
