### ISSUE TITLE
[json-tests] stRevertTest blockchain test failures

### ISSUE THREAD

**Issue by dvdplm** [openethereum/openethereum#11073]
After https://github.com/paritytech/parity-ethereum/pull/11054  the following JSON tests fail in [`stRevertTest`](https://github.com/ethereum/tests/tree/b64fd32dd897285a3884f68b40cee358a4b3c54f/LegacyTests/Constantinople/BlockchainTests/GeneralStateTests/stRevertTest) and are added to the list of skipped tests in `ethcore/res/ethereum/tests-issues/currents.json`.

```
"RevertPrecompiledTouch_d0g0v0_Byzantium",
"RevertPrecompiledTouch_d0g0v0_Constantinople",
"RevertPrecompiledTouch_d0g0v0_ConstantinopleFix",
"RevertPrecompiledTouch_d0g0v0_EIP158",
"RevertPrecompiledTouch_d3g0v0_ConstantinopleFix",
"RevertPrecompiledTouchCC_d0g0v0_Byzantium",
"RevertPrecompiledTouchCC_d0g0v0_Constantinople",
"RevertPrecompiledTouchCC_d0g0v0_EIP158",
"RevertPrecompiledTouchDC_d0g0v0_Byzantium",
"RevertPrecompiledTouchDC_d0g0v0_Constantinople",
"RevertPrecompiledTouchDC_d0g0v0_EIP158",
"RevertPrecompiledTouchExactOOG_d7g1v0_ConstantinopleFix",
"RevertPrecompiledTouchExactOOG_d31g1v0_ConstantinopleFix",
"RevertPrecompiledTouch_storage_d3g0v0_ConstantinopleFix",
"RevertPrecompiledTouch_storage_d0g0v0_ConstantinopleFix"
```

Fix the tests and "un-skip" them.

NOTE: of the above all are fixed except two by applying @debris's fix from #10923 to `ethcore/machine/src/executive.rs`:

```
+                                       let ripemd = Address::from_low_u64_be(3);
+                                       if un_substate.touched.contains(&ripemd) {
+                                               substate.touched.insert(ripemd);
+                                       }
```

Failing blockchain tests with the above:

```
"RevertPrecompiledTouchExactOOG_d7g1v0_ConstantinopleFix",
"RevertPrecompiledTouchExactOOG_d31g1v0_ConstantinopleFix",
```

**Comment by voith** [comment]
@dvdplm The same tests are failing in `py-evm` https://github.com/ethereum/py-evm/pull/1852.
Did you get time to dig into these? 
Since these tests are failing for two clients could this be an error in the upstream tests?

**Comment by adria0** [comment]
@dvdplm I think that I found what is happening here,

For instance, the test `RevertPrecompiledTouchExactOOG_d7g1v0_ConstantinopleFix` has the initial account `0000000000000000000000000000000000000008` (nonce=0,balance=0,code=0x) in the state trie. In the test, a call to this `0000....0008` address is done, with no changes in its state, and this account is cached. When `State::kill_garbage()` is executed, the function detects that the account `exists_and_is_null()`  so `kill_account(...)` it.

Looking at the state trie root hash of go-ethereum, it does not kill this account, and it keeps alive. So OE  differs how go-ethereum performs some check there.

Since this is in the precompile space, I tried to restrict account killing in precompiles `>0xffff`. Unfortunately, there is another test there `failed_tx_xcf416c53_d0g0v0_ConstantinopleFix` that seems that checks in the opposite direction: the account `0000...0003` (nonce=0,balance=0,code=0x) should be killed after the test. I did not dig a lot into the code but it seems that is calling contracts from 0x00 till  0x2b with zero gas.

I'm going to check how go-ethereum is exactly managing this, but maybe something comes to your mind with this info.

**Comment by ordian** [comment]
the `0000...0003` is the `rimemd` address and it is treated differently for some legacy reasons, see the discussion and links in #10923

**Comment by adria0** [comment]
It seems that, when a "pre" allocation is done for accounts in the precompile space, geth (the filler of the tests) is calling the precompiles and OE is calling the code specified in the "pre" block. Asking for clarification.

https://github.com/ethereum/go-ethereum/issues/20926
