### ISSUE TITLE
Incorrect value for block.gaslimit in calls via etherscan. 

### ISSUE THREAD

**Issue by rstormsf** [openethereum/openethereum#11122]
https://kovan.etherscan.io/address/0x8381995934Fea386A17735b35c3e27C1525f4058#readContract

- **Parity Ethereum version**: v2.6.2-beta-25936ae-20190829
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: no / yes

For some reason it returns MAX 2**256 value (int overflow)

**Comment by joshua-mir** [comment]
@rstormsf can you confirm whether this actually happens when that method is called onchain? it is probably the case that when the function is called externally to the evm (ie, web3.js, evmbin, during gas estimation, etc.), the environment that it runs in provides an uncapped gasLimit and that is what you are seeing on etherscan.

**Comment by rstormsf** [comment]
it's called on chain. when I deployed the same contract to rinkeby, goerli, ropsten, I don't see that issue (probably because geth handles it correctly) 

https://rinkeby.etherscan.io/address/0x428cb2e0b190076cf9df9eca7efc00646c755d8f#readContract

**Comment by joshua-mir** [comment]
@rstormsf calls to readContract in etherscan *don't* happen on-chain; I meant if you called that function from another contract as part of a transaction on-chain, I'd suspect the value would be correct. if the clients behaved differently on-chain, we would know because there would be a consensus issue immediately on any contract using that opcode, so this is either an issue in evmbin, web3, or something *inside Aura specifically* if it is on-chain.

**Comment by rstormsf** [comment]
@joshua-mir 
It makes sense to me now. You are right. onchain works as expected.

https://kovan.etherscan.io/address/0xddbb25584bc315ac02fe685b6f8fb0abbcc00cab#readContract

I made a fn call and recorded value in storage
https://kovan.etherscan.io/tx/0x8a49707a358c623d77baedde1c6b50e350a15e2f5bba7dd005f646df3aa8adc3

**Comment by rstormsf** [comment]
why is this issue closed ? @dvdplm @joshua-mir 
isn't it an issue with parity?

**Comment by joshua-mir** [comment]
@rstormsf we'd have to sync up with etherscan and ask what they are using for doing offchain calls, but the fact is that if they were using a simple eth_call on parity itself, this would not be happening (at least, I can't replicate locally, if you see something different then this would be an issue) and if they are using evmbin, they can specify the block gasLimit per query, so it being incorrect would indicate they are leaving it on its default and that's simply a misconfiguration issue on their end.

**Comment by rstormsf** [comment]
@joshua-mir it has NOTHING to do with etherscan itself. There is an issue in parity json rpc 
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{ "to": "0x8381995934Fea386A17735b35c3e27C1525f4058", "data": "0xb295a00e" }],"id":1}' https://kovan.infura.io
```
{"jsonrpc":"2.0","id":1,"result":"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"}

**Comment by joshua-mir** [comment]
Alright, thanks for confirming that

**Comment by rstormsf** [comment]
@joshua-mir I'd remove tags "question", "annoyance" and add "bug" tag
