### ISSUE TITLE
failed to run custom build command for `librocksdb-sys v6.6.4`

### ISSUE THREAD

**Issue by noahsalvadordenjo** [openethereum/openethereum#11634]
following the setup guide
```
cargo build
```
gives me the following error
```
error: failed to run custom build command for `librocksdb-sys v6.6.4`
Caused by:
  process didn't exit successfully: `/home/noahbergh/parity/target/debug/build/librocksdb-sys-407fd74706f294de/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)
--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a
 path where one of these files can be found (invalid: [])"', /home/noahbergh/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.2/src/lib.rs:1956:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```
I had to use
```
rustup default stable
```
instead of
```
rustup default stable-x86_64-pc-windows-msvc
```
according to the rust community
https://github.com/rust-lang/rustup/issues/2283#issuecomment-612007145

**Comment by ordian** [comment]
wait, you're building on linux, but following the instructions for windows?

the error you're having is likely to missing `llvm` package
https://github.com/rust-rocksdb/rust-rocksdb#requirements

**Comment by lz931585538** [comment]
Hello, I have the same question like you.
Would you mind telling me how you sovled this problem?
Thank you!

**Comment by noahsalvadordenjo** [comment]
Well, I was following the instructions for windows while i should have used the instructions for linux

**Comment by lz931585538** [comment]
> Well, I was following the instructions for windows while i should had used the instructions for linux

But I used the instructions for windows and had the same question like you.

error: failed to run custom build command for `librocksdb-sys v6.6.4`

Caused by:
  process didn't exit successfully: `D:\code\Rust\openethereum-master\target\debug\build\librocksdb-sys-614a565fd727c2a2\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/
cargo:warning=couldn't execute `llvm-config --prefix` (error: 系统找不到指定的文件。 (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'clang.dll\', \'libclang.dll\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.53.2\src/lib.rs:1956:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
