### ISSUE TITLE
How can I use a Parity account recovery phrase from 2017?

### ISSUE THREAD

**Issue by daniel-jozsef** [openethereum/openethereum#11653]
Hi people. Sorry for the weird question, but it appears Parity v1.x versions aren't hosted any more, and I need to get my stuff out of this old recovery phrase... All I need is to convert the phrase into a keypair that I can then import to MEW or Metamask, and move all the assets out. So I thought I'd fire up a Parity v1.x Docker image, have it not connect to any blockchain, recover my account and export the keypair... Only Parity v1.x is no longer on Docker, nor do the download links work in Github releases.

Also, apparently Parity v1 did HD wallets differently from eg. Metamask, as all addresses start with 0x00... So it's not like I can use any other HD wallet either.

I believe as the maintainers of the Parity codebase, you guys have a huge responsibility to provide a recovery path, even it's decided to keep it an outside thing.

**Comment by adria0** [comment]
@daniel-jozsef, maybe parity tech - the original company that created the software - has a copy of the old version, https://www.parity.io/

**Comment by dvdplm** [comment]
> I believe as the maintainers of the Parity codebase, you guys have a huge responsibility to provide a recovery path, even it's decided to keep it an outside thing.

`parity-ethereum`, like `openethereum` is OSS and free of use for you and everyone else in perpetuity. It is also provided without any guarantees of any kind, which reflects the amount of money you paid for it (zero). Lecturing others about what their responsibilities to you are is rude at best and does not lead to a constructive conversation. Please weigh your words carefully.

You can download the source code for any version from the releases page and build&run the binary yourself, e.g. [1.11.8-stable sources, zipped](https://github.com/openethereum/openethereum/archive/v1.11.8.zip). Be advised that old releases may contain (known) security issues fixed in subsequent releases so be especially careful about accepting external network connections to your node, maybe using `--mode offline` and/or strict firewall rules. You also may need to use an old rust toolchain (and the same caveat apply: old compilers and libraries may have exploitable security issues).

Good luck!

**Comment by pheuberger** [comment]
Thanks for the pointer @dvdplm. I'm in the same boat and will try to get it to run 👍

**Comment by pheuberger** [comment]
I was able to build it, but the problem is how do I export the key pair from it? I think I used the local web version, but I'm a bit lost how I would fire it up. All I was able to get was the parity command line application (I think). Do you have any pointers for me?

**Comment by dvdplm** [comment]
> Do you have any pointers for me?

TBH that was before my time. :( 

Maybe @q9f remembers roughly how it was done?

**Comment by pheuberger** [comment]
Don't worry, I made it work! 🎉 I found an old Electron client to connect to the API and was able to export the json file.

I'll write up a little guide for the next poor soul that runs into this tomorrow.

**Comment by q9f** [comment]
This has a special release tagged `parityenabled`

https://github.com/MyEtherWallet/etherwallet/releases/tag/v3.9.0

See also this guide: https://www.reddit.com/r/ethereum/comments/bd5dys/restore_parity_wallet_from_mnemonic_option_not/

**Comment by rakita** [comment]
Seems resolved

**Comment by daniel-jozsef** [comment]
Yes, thanks for everyone's help. In the end I followed @q9f's suggestion and succeeded in retrieving my keys.
