### ISSUE TITLE
Openethereum 3 does not sync for ETC chain

### ISSUE THREAD

**Issue by astudnev** [openethereum/openethereum#11842]
Problem described in 

https://twitter.com/q9fmz/status/1289626131377856514
https://hackmd.io/@cUBb4hAvQciAEPoU2yfrzQ/Skd4X6MZw

And we faced with this

**Comment by sorpaas** [comment]
This 51% attack/split is not a bug in OpenEthereum. We also don't support Ethereum Classic any more since middle of last month.

The default maximum reorg depth in OpenEthereum is quite safe under normal (non-51%) operations.

ETC miners, exchanges and users are looking for answers of this 51% attack/split. This is not something we can do anything about even we want to. So honestly [Afri's](https://twitter.com/q9fmz/status/1289626131377856514) attributing the split to an unrelated entity is not only unethical, but also quite scammy.
