### ISSUE TITLE
Config options without CLI behind them

### ISSUE THREAD

**Issue by tomusdrw** [openethereum/openethereum#2913]
It should be possible to create config entries without creating additional CLI options.
or
We should have `--help` and `--help --verbose` :)

**Comment by guanqun** [comment]
This looks like small enough issue for me to dive in, but I don't quite get what you mean. Do you mean we should support `--help --verbose` instead of reporting `Unknown flag`?

**Comment by rphmeier** [comment]
@guanqun Right now our help message is really big. The feature here is to reduce the CLI help to only essential options unless specifying `--verbose` to make the message more approachable.

**Comment by guanqun** [comment]
Ah, I got it. It's like `git help` vs `git branch --help`. :)

**Comment by rphmeier** [comment]
Yep, something like that. I think this would be an awesome opportunity to port our CLI to [clap](https://github.com/kbknapp/clap-rs) over docopt, but that would be a much larger change.

**Comment by tomusdrw** [comment]
The issue here is also that currently any option that is available in config file needs to have a CLI argument, we can start with a possibility to have config options without CLI flag behind them and move some advanced CLI options to config files.

**Comment by guanqun** [comment]
From the comments we want to do two things:

- convert docopt to clap
- remove some advanced CLI arguments. For this one, I don't think I'm in the right position to say which one should be removed. :) Hopefully someone can come up a list.

**Comment by axelchalon** [comment]
I'm currently porting the CLI to clap (#2066) and it will then be possible to have options that can only be set from config files. It would also be possible to find a middle ground by having each subcommand have its own help message (i.e. ``parity account --help``) for example.

**Comment by debris** [comment]
any update on this?

**Comment by axelchalon** [comment]
Marek:

**Separating global help from help of subcommands**
`parity --help` only shows global options, and the options for a specific subcommand are shown by `parity account --help` for example, so this already reduces the size of the help outputs in general.

**Hiding some options from the CLI help output**
Currently, the `parity --help` output (for the global options only) is generated by us (this lets us divide the options into categories in the help output, etc.), so we could decide for example to not show the options if they, say, have an empty help message. This would be easy to implement. For this to also work for subcommands help outputs (`parity account --help`), we could generate those outputs ourselves rather than let Clap automatically do it, or more simply internally use `.hidden()` on clap args. Anyway, this would be doable.
I would imagine that it's best to show all the available options in `--help` but do you have some in mind that shouldn't appear?

**Short help vs long help**
Clap supports `-h` for displaying a short help output, and `--help` for displaying the long help output (like this `--help --verbose` that you were discussing). Currently we only have a single help message for each option.
Using this feature would mean being able to specify a short help and a long help message for each option. This could make the CLI `mod.rs` quite big.
We could also derive the short help message from the long help message; it could be its first sentence. What do you think?

**Comment by 5chdn** [comment]
Thanks for continuously working on this @axelchalon.

I have a proposal, could we somehow format the help output that it does not extend 80 (or 120?) chars in width? It is not very readable on wide screens. Thanks :)

**Comment by axelchalon** [comment]
@5chdn : Sounds good! Working on this.

**Comment by axelchalon** [comment]
PR #7626 *Wrap --help output to 100 characters; update Clap dependency*

**Comment by folsen** [comment]
@axelchalon What is the current status of this? Could we get a summary on this issue and an actionable list of what needs to be done so that someone can pick this up. This is potentially an issue we could create a bounty for.

**Comment by axelchalon** [comment]
Sure! First off, to clarify: @tomusdrw could you specify what your thoughts are behind this issue? I imagine you find the current output of `--help` too long. When printing the help by default (in non-verbose mode), would for example shortening the help messages for each option, or skipping some rarely used options be good solutions for you?

**Comment by vs77bb** [comment]
Hi @folsen @axelchalon I'll hold off posting the bounty until the scope is clarified 👍

**Comment by rphmeier** [comment]
@axelchalon sounds like basically the same thing. `--help` and `--help --verbose` being different, but the config TOML still being able to affect those flags might be enough. But we might want to go a step further and have config options that are not CLI flags at all.

**Comment by 5chdn** [comment]
Can we remove "Legacy Options" from `--help`?

**Comment by 5chdn** [comment]
> Can we remove "Legacy Options" from `--help`?

Can help out here, just couldn't figure out how to hide them without breaking the whole logic of managing the CLI options.

**Comment by axelchalon** [comment]
@5chdn wrapping `if $group_name != "Legacy options" { ... }` around https://github.com/paritytech/parity/blob/dec390a89fe038337399315daf15e628ffbb4d8e/parity/cli/usage.rs#L446-L509 does the trick.

**Comment by lazaridiscom** [comment]
I just hit on this. Trying to get some help, and `parity --help` responds with an endless list of options.

This is not helpful, and it makes a totally unprofessional impression.

So possibly this issue here should get its priority raised, as its in essence a bug.

**Comment by adria0** [comment]
Closing the issue due to its stale state
