### ISSUE TITLE
EIP1559 Transaction Replacement Logic

### ISSUE THREAD

**Issue by mdben1247** [openethereum/openethereum#506]
- **OpenEthereum version (>=3.1.0)**: 3.3.0-rc.6
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

I am getting transactions rejected by the node with message: `"Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce."`. That is even though `max_fee_per_gas` and `max_priority_fee_per_gas` are both bumped by 12,5% and the base_fee has not changed in the meantime.

What is the current logic for EIP1559 transaction replacement?

Looking at geth implementation it seems both fields should be bumped.
https://github.com/ethereum/go-ethereum/blob/master/core/tx_list.go#L279

Looking at openethereum implementation I found the following, but I am unsure how to interpret the code. How concretely `effective_gas_price()` works, what's the value of `tx.gas_price` field in eip1559 context and which `block_base_fee` it refers to - the latest block or the next anticipated? Anyway, the logic seems different to geth, shouldn't it be the same to enable effective transaction propagation between the two clients?

https://github.com/openethereum/openethereum/blob/5d9ff63043bb5986a8045935f1a25e2bfa6239fd/crates/ethcore/types/src/transaction/transaction.rs#L635
https://github.com/openethereum/openethereum/blob/5d9ff63043bb5986a8045935f1a25e2bfa6239fd/crates/concensus/miner/src/pool/scoring.rs#L97

**Comment by sunce86** [comment]
In order to replace the tx you need to bump the effective_gas_price by 12.5%, where:
effective_gas_price = min(pending_block_base_fee + maxPriorityFeePerGas, maxFeeCapPerGas)

To get pending_block_base_fee, call eth_getBlockByNumber('pending')

Here is a code snippet how to bump feeCap and tip to replace the tx:
while new.effective_gas_price(pending_block_base_fee) - old.effective_gas_price(pending_block_base_fee) < desired_gas_bump {
  if maxFeePerGas < maxPriorityFeePerGas + pending_block_base_fee {
    //increase maxFeePerGas by 1 gwei
  } else {
    //increase maxPriorityFeePerGas by 1 gwei
  }
}
desired_gas_bump is hardcoded to 12.5%

Also, tx.gas_price field in eip1559 context refers to the maxFeeCapPerGas.

Also, you pointed to the right functions in your question. Function "choose" is used for replacement logic.

**Comment by mdben1247** [comment]
Thanks. I guess what has me confused is this line which does the min() comparison to `self.tx().gas_price`. Is that the same as maxFeeCapPerGas as in your example for effective_gas_price calculation?

https://github.com/openethereum/openethereum/blob/5d9ff63043bb5986a8045935f1a25e2bfa6239fd/crates/ethcore/types/src/transaction/transaction.rs#L638
