### ISSUE TITLE
Block information is incomplete while ancient block sync is still in progress

### ISSUE THREAD

**Issue by ulyanas** [openethereum/openethereum#582]
Original issue: https://github.com/openethereum/parity-ethereum/issues/10777 

Occasionally is still reproduced on OpenEthereum. 

Need to investigate.

**Comment by rimrakhimov** [comment]
For now it seems that the node causing such an error was synchronized without `--no-warp` option. One of the solutions may be to re-synchronize nodes with `--no-warp`.

In general, even without `--no-warp` option the node should download ancient blocks in the background and finally synchronize and have all blocks available (if `--no-ancient-blocks` option was not used). However, it seems that the node had invalid first missing ancient block number saved. Due to that reason, the synchronization of missing blocks did not occur. However, it might be too difficult to investigate the reasons of such behavior. We may try to explicitly update the value that corresponds to the first ancient block number in the database.

**Comment by rimrakhimov** [comment]
Synchronizing node with `--no-warp` option helped. Will close the issue.
