### ISSUE TITLE
Get the light client to compile for iOS

### ISSUE THREAD

**Issue by tomaka** [openethereum/openethereum#7955]
So that it can be used as a library by application, or as a background service (if that's possible on iOS).

**Comment by rphmeier** [comment]
cc https://github.com/paritytech/parity/issues/4842

**Comment by tomaka** [comment]
I could tackle the technical part of this, but I don't have any iPhone, Mac or Apple device in general.

**Comment by 5chdn** [comment]
Let's get you some devices then. :computer:

**Comment by ratake** [comment]
I got parity compiling for and running on iOS – it was fairly straightforward because iOS is very similar to macOS. The changes I had to make were:
- Disable USB hardware wallet support
    - Did this by commenting things out, not sure of the best location for the target/feature flag checks.
- https://github.com/alexcrichton/cc-rs/pull/285
- Update [snappy-sys](https://github.com/paritytech/rust-snappy) to use the above `cc-rs` instead of `gcc-rs`
- Patch [heapsize](https://github.com/servo/heapsize) to work for [non-jemalloc builds](https://github.com/servo/heapsize/issues/80) (i.e. to use system provided `malloc_usable_size`)
    - This is complicated to upstream because there is no way to detect at compile time which allocator is being used.

**Comment by ratake** [comment]
It would still need #4842 to be usable inside of an iOS app or extension (also light syncing needs some love in general).

**Comment by rphmeier** [comment]
@ratake nice work! it's true, we do need a library as well as better light sync. #8075 should address some of the syncing issues but beyond that we need stronger guarantees from the consensus layer.

**Comment by tomaka** [comment]
I've looked a bit into this issue today, as I had exceptionally access to a Mac.

The heapsize situation is quite problematic.
We should be able to replace it with the `malloc_size_of` crate of servo, but that means we have to propagate the change throughout the dependency tree.

**Comment by tomaka** [comment]
We also need `cc-rs` to pass a flag to the linker when building a library. Unfortunately, the `rust-crypto` crate still uses `gcc-rs` and doesn't seem to be maintained anymore. Hence the build fails.

Either we fork `rust-crypto` to use `cc-rs`, or we remove the `rust-crypto` dependency entirely. I would suggest the latter.

**Comment by adria0** [comment]
Closing issue due to its stale state.
