### ISSUE TITLE
Significantly reduce Archive Node size

### ISSUE THREAD

**Issue by 5chdn** [openethereum/openethereum#7967]
Current size: 850GB.

Any ideas how to keep this below <1 TB long term - be my guest.

**Comment by tjayrush** [comment]
I have an idea. I'm not sure it's quite what you have in mind, but this would work for me.

I run two different nodes on two different machines: (1) an archive node (which takes up >800GB of hard drive space), and (2) a trace-only node (which takes up about 80GB).

I run the trace node because I am "auditing" the chain for my own set of accounts. The idea is: "Yes. The node is a great accounting system, but I want to keep track of my ether off chain just in case." Some people call this per-block reconciliation. In order to do this, I watch the end of the chain (actually 20 blocks prior to the end of the chain to avoid re-orgs) and "pick off" transactions on the accounts I'm watching. At each transaction, I check the account balance from the node against my own internally maintained balance. If I find a mistake, then I've probably missed a transaction. This "double-check" is the only way I know if I'm building an accurate per-account list of transactions.

The trouble comes when I want to audit a new account. In this case, I need to go revisit history and scan the entire chain for transactions on that new address. I could do this on the trace node, but then I would not have historical balances to double check that my list is correct. This is why I also run the archive node. Without the ability to double check historical balances, I have no way to know if I've missed transactions.

**My suggestion:** Add a mode half way between archive and trace that preserves historical account balances but none of the other historical state (no storage or code). In this way, I can be certain that I have an accurate list of transactions on a given account. I would then have confidence that I could accurately rebuild the other state if I need to. In other words, an option like `--pruning balances` which would keep only historical balances but delete all other historical states.

With a trace only node, there is no way to doublecheck a list of transactions on an account is accurate. With pruning "archive" one must have a very large TB hard drive.

**Comment by tomusdrw** [comment]
Another suggestion:
Use dynamic checkpointing and if the required state is not available, go to the checkpoint and re-compute the requested state.
Such pruning might not be easy to implement, but perhaps we can have a separate thread that periodically attempts to remove some states (not sure if we have enough information in the state tree nodes to prevent deleting entries that are used in some other states).

**Comment by debris** [comment]
should reduce size (not significantly) #7979 #7934

**Comment by 5chdn** [comment]
Splitting the database into multiple disks does not address this issue directly, but would allow users to plug some devices together based on availability.
