### ISSUE TITLE
Replace Tendermint engine with Substrate PoC-1 engine

### ISSUE THREAD

**Issue by folsen** [openethereum/openethereum#8664]
The Tendermint consensus engine has gone unmaintained for a while, we should make a decision whether we update and maintain it and write a test-suite etc necessary to keep this in shape, or if we remove it until we have a more concrete user for it. I would vote remove.

@rphmeier @andresilva might be interested in chiming in.

**Comment by rphmeier** [comment]
I am planning to move the substrate PoC-1 consensus engine out of tree. It is really similar to tendermint; perhaps we can use it in Parity as well. Changes necessary to support this:
  - allow multiple valid seals per block (any 2/3+ majority signoff). requires building the chain based on `parent_hash = parent.bare_hash()` instead of `parent.hash()`.
  - have engine's block production be a `Future` (as the implementation is async)

**Comment by julien-marchand** [comment]
We are using Tendermint for a project (see previous [issue](https://github.com/paritytech/parity/issues/8235)).

The need is an instant finality PoA compatible with ValidatorSets so Tendermint is a good candidate but as far as I understand, Substrate PoC-1 would also be a good candidate, right?

**Comment by rphmeier** [comment]
Yep, Substrate PoC-1 fulfills those needs as well.

**Comment by d10r** [comment]
We want to use Parity with Tendermint for a public chain and were evaluating 2 options:
* fixing / improving / optimizing the existing native implementation
* create an [Ethermint](http://ethermint.readthedocs.io/)-style Parity based [ABCI](http://tendermint.readthedocs.io/en/master/introduction.html#abci-overview) app and use it with the [Go Tendermint](https://github.com/tendermint/tendermint) reference implementation

Yesterday I had the great opportunity to talk to @andresilva and other Parity devs at Rustfest who pointed me to this ticket. So there now seems to be a 3rd option:
* use the *Substrate PoC-1 engine* instead of Tendermint

@rphmeier everybody pointed me to you as being the one able to answer some of the questions I still have, e.g.
* what are the reasons for phasing out the existing Tendermint implementation? Is it just that there's currently no maintainer (with @keorn nomore available) or does it have architectural flaws which would require a rewrite anyway? If it's just about a maintainer, we may be able to take on that role (it's not yet on github, but [we](http://lab10.coop/) are already working on the Parity codebase - not yet engine related).
* what exactly is *Substrate PoC-1 engine*? What's the differences to Tendermint? Is there any documentation of it except of the actual implementation? (btw. I find the construction with `BftFuture` pretty cool!)
* are performance characteristics of this engine already known? Are optimizations like the *epidemic gossip protocol* (as described [here](http://tendermint.readthedocs.io/projects/tools/en/v0.14.0/specification/byzantine-consensus-algorithm.html?highlight=gossip#background-gossip)) included / planned / possible? (I'm not yet an expert in this, but my understanding is that such optimizations are important for BFT engines because fundamentally they have O(2) complexity)

**Comment by rphmeier** [comment]
@d10r Right, for one there's no maintainer, and it's also not a proper tendermint implementation AFAIK, because it requires the proposer himself to commit instead of treating any 2/3+ set of commit messages as a seal.

The Substrate PoC-1 engine is pretty close to tendermint in terms of performance, design, and security. It was just meant to be a simple consensus engine to implement in an asynchronous manner. It is communication-agnostic, provided the communication meets the assumptions of the engine, so we could do something like epidemic gossip. There are some informal docs in the `w3f/polkadot-spec1` repo.
