### ISSUE TITLE
Gas used according to transaction trace doesn't match transaction receipt

### ISSUE THREAD

**Issue by antonislav** [openethereum/openethereum#9178]
> I'm running:
>
> - **Which Parity version?**: 1.10.4
> - **Which operating system?**: MacOS 
> - **How installed?**: via binaries 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

It appears that the amount of used gas according to the transaction traces (obtained by the RPC call `trace_block`) doesn't match the amount according to the transaction receipt (obtained by the RPC call `eth_getTransactionReceipt`).

Here is one concrete example, for the transaction hash `0xcbaa1b514a4565003fa0708a21cf0ddb115ab20d2c9373ffda0c129d1deaeebc`:

transaction trace:
```
{
  'action': {
   'callType': 'call',
   'from': '0xe09c68e61998d9c81b14e4ee802ba7adf6d74cdb',
   'gas': '0x6ee4',
   'input': '0x454e32413658483230',
   'to': '0x2910543af39aba0cd09dbb2d50200b3e800a63d2',
   'value': '0xde0b6b3a7640000'
  },
  'blockHash': '0xc77c370a5e4f12e8e0b20e8435132a04d474a02323c86077d678cbaba2af5905',
  'blockNumber': 47505,
  'result': {'gasUsed': '0x0', 'output': '0x'},
  'subtraces': 0,
  'traceAddress': [],
  'transactionHash': '0xcbaa1b514a4565003fa0708a21cf0ddb115ab20d2c9373ffda0c129d1deaeebc',
  'transactionPosition': 0,
  'type': 'call'
}
```

transaction receipt:
```
{
 'blockHash': '0xc77c370a5e4f12e8e0b20e8435132a04d474a02323c86077d678cbaba2af5905',
 'blockNumber': '0xb991',
 'contractAddress': None,
 'cumulativeGasUsed': '0x546c',
 'gasUsed': '0x546c',
 'logs': [],
 'logsBloom': '...',
 'root': '0x22a37344703dea06565d297e334469810a512ceded1617681df783ee1e1cb9f2',
 'status': None,
 'transactionHash': '0xcbaa1b514a4565003fa0708a21cf0ddb115ab20d2c9373ffda0c129d1deaeebc',
 'transactionIndex': '0x0'
}
```

According to the transaction receipt the amount of used gas is `0x546c` or `21612`. However the transaction trace contains the amount `gas = 0x6ee4` or `28388`, which is **larger** then the value in the transaction receipt. There is also the value `result.gasUsed = 0` which is, obviously, also not correct.

**Comment by debris** [comment]
thanks for the report

something really weird is happening here:

https://etherscan.io/tx/0xcbaa1b514a4565003fa0708a21cf0ddb115ab20d2c9373ffda0c129d1deaeebc

gas_limit: 50.000
gas_used: 21612
gas in transaction_trace: 28388 (which is 50.000 - 21612)

**Comment by debris** [comment]
lol, found the issue.

over here we create a variable `init_gas`. It's already reduced by `base_gas_required`  which is 21k for a transaciton call + cost of attaching data to it

https://github.com/paritytech/parity-ethereum/blob/7e6a571cbaa164a7d17824a1a40dc357e8dbcf13/ethcore/src/executive.rs#L258

and we initiate `ActionParams` with it

https://github.com/paritytech/parity-ethereum/blob/7e6a571cbaa164a7d17824a1a40dc357e8dbcf13/ethcore/src/executive.rs#L319-L329

and then we call `prepare_trace_call` with those `ActionParams`. 

https://github.com/paritytech/parity-ethereum/blob/7e6a571cbaa164a7d17824a1a40dc357e8dbcf13/ethcore/src/executive.rs#L413

That's why the gas is invalid

**Comment by debris** [comment]
same issue #6964

**Comment by debris** [comment]
#8015
