### ISSUE TITLE
separate build targets for light clients/mode and execution profile

### ISSUE THREAD

**Issue by ni3gavhane** [openethereum/openethereum#9483]
is it possible to have separate build targets for light clients/mode? 
The other question I have is, if we look at the execution profile there are total 53 threads spawned and the distribution looks like below. so do we need all these threads running for light mode? 
![light_profile](https://user-images.githubusercontent.com/43007217/45104880-455d7000-b133-11e8-9b53-4f38ace45e56.png)

**Comment by niklasad1** [comment]
@ni3gavhane 

Hey,
That's an excellent question and currently, the answer is no, unfortunately.
However, we will be started to look into it soon since one of our goals is to compile the light-client to WebAssembly but first, we have some other critical issues to fix first!

**Comment by Tbaut** [comment]
@ni3gavhane we've been talking internally about it, such changes seem involved and will probably not happen in the near future. Can you be more precise in why this is a blocker for you?

**Comment by Tbaut** [comment]
Hey Nitin, just dropping here what we discussed in dm, it would be great if you can describe precisely what devices you wish to use the light client on, along with the problems that you currently encounter so that we can address them.

**Comment by EBGToo** [comment]
Hi.  Not sure our need falls under this issue... we are planning to deploy multiple Parity nodes to our cloud infrastructure with the sole/primary goal of serving our PIPv1-compatible app for mobile devices.  Would like to have a Parity distribution focused on such a goal - accepting ~25 eth62/63 peers but 1,000s of PIP peers.

**Comment by niklasad1** [comment]
@ni3gavhane

FYI, you can control the number of threads by the CLI argument ```--num-verifiers``` and I just fixed a bug in that code so that should be possible set to this to 1 for a minimal config.

This is under our radar and we will fix some things in the existing code base to help reduce the number of threads in the codebase meanwhile. 

We would appreciate if can you can be more explicit what devices you plan to run the light client on, with regard to binary size, memory usage and so on as @Tbaut said!

**Comment by adria0** [comment]
Closing the issue due to its stale state
