### ISSUE TITLE
PIPv1 Provides no Transaction Error Status.

### ISSUE THREAD

**Issue by EBGToo** [openethereum/openethereum#9817]
If a transaction is submitted that when processed exposes some kind of error (incorrect nonce, not enough gas, insufficient funds, etc), then there is no mechanism by which the submitter can learn of the error status.

For a light client using PIPv1, one must timeout on waiting for the transaction to be included and then, essentially, guess/compute the error reason.

Perhaps the PIPv1 Request:Execution message is meant to ensure that a transaction is properly constructed?  If so, a 'race condition' between proving the execution and the actual submission means that the submission could still fail.  The Request:Execution does not include the 'nonce', nor signature and thus can't actually confirm that a transaction has no errors.

**Comment by niklasad1** [comment]
Hey @EBGToo 

1. We changed the behaviour regarding `bad responses` on requests https://github.com/paritytech/parity-ethereum/pull/9790 basically we take the majority of errors received when a request `times out`
2. insufficient gas and similar needs to be answered by full-node because this information is missing
3. insufficient balance is fixed by https://github.com/paritytech/parity-ethereum/pull/9417

I will close this please reopen if there is something missing, thanks for reporting this!

**Comment by EBGToo** [comment]
Sorry, my question was about the PIP protocol, not your light client and not about the JSON-RPC interface.

Top-level: When using PIPv1, if I submit a transaction that has a flaw (like insufficient funds), how will the peer respond back to me?

I've seen such a flawed transaction disappear, completely.  No indication of failure anywhere.

**Comment by EBGToo** [comment]
FYI: For our Parity/PIP, Geth/LES wallet app (for IOS/Android) we support the App with multiple Ethereum Nodes (Parity and/or Geth).  Because of this issue, we have been forced to a) deploy additional Geth nodes and b) disable PIP w/i our Apps.

Yes, we try hard to have the User-initiated transaction to be utterly correct; but when it is not, we need some feedback.

**Comment by adria0** [comment]
Closing issue due to its stale state.
